"""fase 1 - cliente, plano, usuario, audit_log, sessao_log

Revision ID: 91b122f37431
Revises: 
Create Date: 2026-08-30 18:37:04.912990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91b122f37431'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acao', sa.Text(), nullable=False),
    sa.Column('entidade', sa.Text(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('depois', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_entidade', 'audit_log', ['entidade', 'entidade_id'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('razao_social', sa.Text(), nullable=False),
    sa.Column('nome_fantasia', sa.Text(), nullable=True),
    sa.Column('cnpj', sa.Text(), nullable=False),
    sa.Column('cidade', sa.Text(), nullable=True),
    sa.Column('uf', sa.CHAR(length=2), nullable=True),
    sa.Column('status', sa.Text(), server_default='ativo', nullable=False),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cnpj ~ '^[0-9]{14}$'", name='ck_cliente_cnpj_normalizado'),
    sa.CheckConstraint("status IN ('ativo', 'suspenso', 'encerrado')", name='ck_cliente_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('faixa_rollout',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('maquinas_ate', sa.Integer(), nullable=True),
    sa.Column('rollouts_mes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessao_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('papel', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("papel IN ('n1n2', 'n3', 'gestor')", name='ck_usuario_papel'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cliente_contato',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('cargo', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telefone', sa.Text(), nullable=True),
    sa.Column('departamento', sa.Text(), nullable=True),
    sa.Column('eh_responsavel_ti', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fim', sa.Date(), nullable=True),
    sa.Column('tipo_plano', sa.Text(), nullable=False),
    sa.Column('frequencia_visita_dias', sa.Integer(), nullable=True),
    sa.Column('antivirus', sa.Text(), nullable=False),
    sa.Column('backup_m365', sa.Text(), nullable=False),
    sa.Column('suporte_dominio_atualizacao', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('suporte_estendido', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('escopo_fixado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('qtd_estacoes', sa.Integer(), nullable=True),
    sa.Column('estacoes_verificado_em', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.CheckConstraint("(tipo_plano = 'remoto' AND frequencia_visita_dias IS NULL) OR (tipo_plano = 'completo' AND frequencia_visita_dias IN (30, 45))", name='ck_plano_frequencia_por_tipo'),
    sa.CheckConstraint("antivirus IN ('acronis_incluso', 'watchguard_incluso', 'watchguard_direto')", name='ck_plano_antivirus'),
    sa.CheckConstraint("backup_m365 IN ('nenhum', 'sharepoint', 'completo')", name='ck_plano_backup_m365'),
    sa.CheckConstraint("tipo_plano IN ('completo', 'remoto')", name='ck_plano_tipo_plano'),
    sa.CheckConstraint('vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio', name='ck_plano_vigencia_coerente'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ── faixa_rollout: seed + unicidade (briefing 5.1) ──────────────────────
    # Sem seed a tabela existe e a regra de negócio não. NULLS NOT DISTINCT
    # torna o NULL ("acima de 30") único também — duas linhas com o mesmo
    # valor, NULL incluso, tornam a faixa ambígua.
    op.execute("""
        CREATE UNIQUE INDEX ux_faixa_rollout_maquinas_ate
        ON faixa_rollout (maquinas_ate) NULLS NOT DISTINCT;
    """)
    op.execute("""
        INSERT INTO faixa_rollout (maquinas_ate, rollouts_mes) VALUES
            (20, 2),
            (30, 3),
            (NULL, 4);
    """)

    # ── plano: no máximo um vigente por cliente (briefing 4.1, 6.1) ─────────
    # Índice único parcial — sem ele, vigencia_fim IS NULL pode valer para
    # duas linhas do mesmo cliente ao mesmo tempo; a corrupção só aparece
    # quando uma consulta devolve duas linhas e o código pega a primeira.
    op.execute("""
        CREATE UNIQUE INDEX ux_plano_vigente_por_cliente
        ON plano (cliente_id) WHERE vigencia_fim IS NULL;
    """)
    # Lista de colunas EXPLÍCITA, não SELECT * — o Postgres congela a lista
    # de colunas no momento do CREATE VIEW. Com SELECT *, uma alteração
    # futura em `plano` (Fase 2+) faria esta view continuar devolvendo o
    # conjunto antigo de colunas, em silêncio: sem erro, sem aviso, só uma
    # coluna que "não existe" para quem consulta pela view. QUALQUER
    # migration futura que altere `plano` precisa DROP + CREATE desta view
    # de novo — CREATE OR REPLACE VIEW não muda a lista de colunas.
    op.execute("""
        CREATE VIEW plano_vigente AS
        SELECT id, cliente_id, vigencia_inicio, vigencia_fim, tipo_plano,
               frequencia_visita_dias, antivirus, backup_m365,
               suporte_dominio_atualizacao, suporte_estendido, escopo_fixado,
               qtd_estacoes, estacoes_verificado_em, observacoes
        FROM plano
        WHERE vigencia_fim IS NULL;
    """)

    # ── audit_log: índice para "o que este usuário fez" ─────────────────────
    # DESC não tem forma portável no Column/Index do SQLAlchemy declarative
    # nesta versão — só aqui.
    op.execute("""
        CREATE INDEX ix_audit_log_usuario_em
        ON audit_log (usuario_id, em DESC);
    """)

    # ── Append-only real, não decorativo (briefing 3.3) ──────────────────────
    # REVOKE sozinho não vale contra o dono da tabela: em produção,
    # altcom365_app É o dono (é o usuário da DATABASE_URL) — REVOKE dele
    # mesmo não impede um GRANT de volta por ele mesmo. Pega qualquer role
    # FUTURO que não seja dono; o trigger é quem bloqueia de fato, dono
    # inclusive — testado ao vivo nos dois papéis antes deste PR.
    #
    # FOR EACH ROW não dispara em TRUNCATE — é um comando por statement, sem
    # linha OLD/NEW. Sem o trigger de STATEMENT dedicado, TRUNCATE audit_log
    # apaga a trilha inteira sem erro nenhum, mesmo com o trigger ROW ativo.
    op.execute("""
        CREATE FUNCTION portal_log_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'append-only: % nao e permitido em %.% (id=%)',
                TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME, OLD.id;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE FUNCTION portal_log_no_truncate() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'append-only: TRUNCATE nao e permitido em %.%',
                TG_TABLE_SCHEMA, TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION portal_log_append_only();
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_log_no_truncate
        BEFORE TRUNCATE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION portal_log_no_truncate();
    """)
    op.execute("""
        CREATE TRIGGER trg_sessao_log_append_only
        BEFORE UPDATE OR DELETE ON sessao_log
        FOR EACH ROW EXECUTE FUNCTION portal_log_append_only();
    """)
    op.execute("""
        CREATE TRIGGER trg_sessao_log_no_truncate
        BEFORE TRUNCATE ON sessao_log
        FOR EACH STATEMENT EXECUTE FUNCTION portal_log_no_truncate();
    """)

    # REVOKE dentro de um DO block: sem isso a migration quebra em qualquer
    # ambiente onde altcom365_app não exista (local, CI futuro) — o role é
    # específico do banco de produção do Render.
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'altcom365_app') THEN
                REVOKE UPDATE, DELETE ON audit_log, sessao_log FROM altcom365_app;
            END IF;
        END
        $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'altcom365_app') THEN
                GRANT UPDATE, DELETE ON audit_log, sessao_log TO altcom365_app;
            END IF;
        END
        $$;
    """)
    op.execute("DROP TRIGGER IF EXISTS trg_sessao_log_no_truncate ON sessao_log;")
    op.execute("DROP TRIGGER IF EXISTS trg_sessao_log_append_only ON sessao_log;")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_no_truncate ON audit_log;")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_append_only ON audit_log;")
    op.execute("DROP FUNCTION IF EXISTS portal_log_no_truncate();")
    op.execute("DROP FUNCTION IF EXISTS portal_log_append_only();")
    # plano_vigente depende de plano — precisa cair antes do drop_table.
    op.execute("DROP VIEW IF EXISTS plano_vigente;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plano')
    op.drop_table('cliente_contato')
    op.drop_table('usuario')
    op.drop_table('sessao_log')
    op.drop_table('faixa_rollout')
    op.drop_table('cliente')
    op.drop_index('ix_audit_log_entidade', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
