"""fase 2 - ativo, ativo_interface, credencial, segredo_acesso_log

Revision ID: ec4549622c1d
Revises: 91b122f37431
Create Date: 2026-08-31 00:40:24.035007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec4549622c1d'
down_revision: Union[str, Sequence[str], None] = '91b122f37431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segredo_acesso_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('credencial_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=False),
    sa.CheckConstraint("resultado IN ('concedido', 'negado')", name='ck_segredo_acesso_log_resultado'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ativo',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('apelido', sa.Text(), nullable=False),
    sa.Column('marca', sa.Text(), nullable=True),
    sa.Column('modelo', sa.Text(), nullable=True),
    sa.Column('numero_serie', sa.Text(), nullable=True),
    sa.Column('unidade', sa.Text(), nullable=True),
    sa.Column('localizacao', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='ativo', nullable=False),
    sa.Column('instalado_em', sa.Date(), nullable=True),
    sa.Column('garantia_ate', sa.Date(), nullable=True),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("status IN ('ativo', 'reserva', 'baixado')", name='ck_ativo_status'),
    sa.CheckConstraint("tipo IN ('roteador', 'firewall', 'switch', 'ap', 'link', 'servidor', 'nvr', 'nobreak')", name='ck_ativo_tipo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credencial',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('escopo_tipo', sa.Text(), nullable=False),
    sa.Column('escopo_id', sa.UUID(), nullable=True),
    sa.Column('sensibilidade', sa.Text(), nullable=False),
    sa.Column('rotulo', sa.Text(), nullable=False),
    sa.Column('usuario', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('segredo_cifrado', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('chave_versao', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('mfa_observacao', sa.Text(), nullable=True),
    sa.Column('rotacionada_em', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("escopo_tipo IN ('ativo', 'sistema', 'cliente')", name='ck_credencial_escopo_tipo'),
    sa.CheckConstraint("sensibilidade IN ('operacional', 'administrativa')", name='ck_credencial_sensibilidade'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ativo_interface',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('mascara', sa.Text(), nullable=True),
    sa.Column('gateway', postgresql.INET(), nullable=True),
    sa.Column('atribuicao', sa.Text(), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('mac', postgresql.MACADDR(), nullable=True),
    sa.CheckConstraint("atribuicao IS NULL OR atribuicao IN ('fixo', 'dhcp', 'pppoe')", name='ck_ativo_interface_atribuicao'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    #
    # As três linhas de drop_index que o autogenerate propôs aqui (em
    # ix_audit_log_usuario_em, ux_faixa_rollout_maquinas_ate e
    # ux_plano_vigente_por_cliente) foram REMOVIDAS à mão. Os três objetos
    # existem no banco — criados via op.execute() na migration Fase 1,
    # não como Index()/UniqueConstraint() do SQLAlchemy declarative (DESC,
    # NULLS NOT DISTINCT e índice parcial não têm forma portável na
    # versão em uso) — então o autogenerate não os vê no metadata e
    # propõe apagá-los como se tivessem sido removidos do código. Não
    # foram. Apagar e recriar aqui teria o mesmo efeito final no schema,
    # mas por um caminho arriscado à toa: qualquer migration futura que
    # repita este autogenerate vai propor a mesma dupla drop/create de
    # novo, pelo mesmo motivo — o padrão é ignorar essas três linhas
    # sempre, não resolver uma vez.

    # ── Ativo, credencial: novas tabelas, mesmo padrão append-only? NÃO ────
    # ativo e credencial são dado vivo (status muda, senha rotaciona) —
    # só segredo_acesso_log é log. Ver clientes/models.py: ambos ganham
    # DELETE recusado por convenção de aplicação (nenhuma rota o expõe),
    # não por REVOKE — REVOKE DELETE bloquearia até um UPDATE de
    # correção de dado errado que não seja rotação, o que não é a
    # intenção aqui.

    # ── segredo_acesso_log: append-only, mesmo padrão de audit_log/ ────────
    # sessao_log (briefing 3.3). REUTILIZA as funções de trigger criadas
    # na migration Fase 1 (91b122f37431) — portal_log_append_only() e
    # portal_log_no_truncate() são genéricas (usam TG_TABLE_NAME/
    # TG_TABLE_SCHEMA da própria trigger, nada específico de audit_log),
    # recriar a mesma função com outro nome só pra esta tabela seria
    # duplicação sem motivo.
    op.execute("""
        CREATE TRIGGER trg_segredo_acesso_log_append_only
        BEFORE UPDATE OR DELETE ON segredo_acesso_log
        FOR EACH ROW EXECUTE FUNCTION portal_log_append_only();
    """)
    op.execute("""
        CREATE TRIGGER trg_segredo_acesso_log_no_truncate
        BEFORE TRUNCATE ON segredo_acesso_log
        FOR EACH STATEMENT EXECUTE FUNCTION portal_log_no_truncate();
    """)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'altcom365_app') THEN
                REVOKE UPDATE, DELETE ON segredo_acesso_log FROM altcom365_app;
            END IF;
        END
        $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'altcom365_app') THEN
                GRANT UPDATE, DELETE ON segredo_acesso_log TO altcom365_app;
            END IF;
        END
        $$;
    """)
    op.execute("DROP TRIGGER IF EXISTS trg_segredo_acesso_log_no_truncate ON segredo_acesso_log;")
    op.execute("DROP TRIGGER IF EXISTS trg_segredo_acesso_log_append_only ON segredo_acesso_log;")
    # portal_log_append_only()/portal_log_no_truncate() NÃO são derrubadas
    # aqui — pertencem à migration Fase 1 (são usadas por audit_log e
    # sessao_log também), não a esta.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ativo_interface')
    op.drop_table('credencial')
    op.drop_table('ativo')
    op.drop_table('segredo_acesso_log')
    # ### end Alembic commands ###
